# Generated by Django 5.1.4 on 2024-12-25 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpi', '0003_dpi_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('la_date', models.DateField()),
                ('NSS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.patient')),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
