# Generated by Django 5.1.4 on 2024-12-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('les_soins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soins',
            old_name='NSS',
            new_name='patient',
        ),
    ]
