# Generated by Django 5.1.4 on 2024-12-22 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('dpi', '0002_rename_medecin_taitant_patient_medecin_traitant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resume', models.TextField()),
                ('la_date', models.DateField()),
                ('dpi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.dpi')),
                ('etablisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.etablisement')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
