# Generated by Django 5.1.4 on 2024-12-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='medecin_taitant',
            new_name='medecin_traitant',
        ),
    ]
