# Generated by Django 5.1.4 on 2024-12-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0002_rename_medecin_taitant_patient_medecin_traitant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
