# Generated by Django 5.1.4 on 2024-12-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('satisfait', models.BooleanField(default=False)),
                ('date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('descirption', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParamValeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(max_length=255)),
                ('parametre', models.CharField(max_length=255)),
            ],
        ),
    ]
