# Generated by Django 5.1.4 on 2024-12-23 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bilan_bio', '0001_initial'),
        ('consultation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbiologique',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation'),
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='laborantient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biological_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paramvaleur',
            name='bilan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilan_bio.bilanbiologique'),
        ),
    ]
