# Generated by Django 5.1.4 on 2024-12-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilan_bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbiologique',
            name='valeur_reference',
            field=models.FloatField(default=0),
        ),
    ]
