# Generated by Django 5.1.4 on 2024-12-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilan_bio', '0002_bilanbiologique_valeur_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanbiologique',
            name='valeur_reference',
        ),
        migrations.AddField(
            model_name='paramvaleur',
            name='valeur_reference',
            field=models.FloatField(default=0),
        ),
    ]
