# Generated by Django 5.1.4 on 2024-12-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilan_bio', '0003_remove_bilanbiologique_valeur_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramvaleur',
            name='valeur_reference',
            field=models.FloatField(),
        ),
    ]
