# Generated by Django 5.1.4 on 2024-12-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilan_bio', '0003_alter_bilanbiologique_laborantient'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbiologique',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
