# Generated by Django 5.1.4 on 2024-12-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilan_bio', '0004_alter_paramvaleur_valeur_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramvaleur',
            name='valeur_reference',
            field=models.CharField(max_length=255),
        ),
    ]
