# Generated by Django 5.1.4 on 2024-12-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilan_radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanradiologique',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
