# Generated by Django 5.1.4 on 2024-12-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilan_radio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilanradiologique',
            old_name='statifait',
            new_name='satisfait',
        ),
        migrations.RenameField(
            model_name='examenimageriemedicale',
            old_name='examen_image_path',
            new_name='examen_image',
        ),
    ]
