# Generated by Django 5.1.4 on 2024-12-24 20:35

import bilan_radio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilan_radio', '0002_rename_statifait_bilanradiologique_satisfait_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenimageriemedicale',
            name='examen_image',
            field=models.ImageField(blank=True, null=True, upload_to=bilan_radio.models.upload_to),
        ),
    ]
