# Generated by Django 5.1.2 on 2024-12-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('laboratory', 'Laboratory')], default='patient', max_length=255)),
                ('etablisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpi.etablisement')),
            ],
        ),
    ]
