# Generated by Django 5.1.4 on 2024-12-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('medecin', 'Medecin'), ('infirmier', 'Infirmier'), ('laborantin', 'Laborantin'), ('radiologue', 'Radiologue'), ('admin', 'Admin')], default='patient', max_length=255),
        ),
    ]
